/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterviewIndexRouteImport } from './routes/interview/index'
import { Route as InterviewSessionRouteImport } from './routes/interview/session'
import { Route as InterviewResultsRouteImport } from './routes/interview/results'
import { Route as InterviewQuestionsRouteImport } from './routes/interview/questions'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIndexRoute = InterviewIndexRouteImport.update({
  id: '/interview/',
  path: '/interview/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewSessionRoute = InterviewSessionRouteImport.update({
  id: '/interview/session',
  path: '/interview/session',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewResultsRoute = InterviewResultsRouteImport.update({
  id: '/interview/results',
  path: '/interview/results',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewQuestionsRoute = InterviewQuestionsRouteImport.update({
  id: '/interview/questions',
  path: '/interview/questions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/interview/questions': typeof InterviewQuestionsRoute
  '/interview/results': typeof InterviewResultsRoute
  '/interview/session': typeof InterviewSessionRoute
  '/interview/': typeof InterviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/interview/questions': typeof InterviewQuestionsRoute
  '/interview/results': typeof InterviewResultsRoute
  '/interview/session': typeof InterviewSessionRoute
  '/interview': typeof InterviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/interview/questions': typeof InterviewQuestionsRoute
  '/interview/results': typeof InterviewResultsRoute
  '/interview/session': typeof InterviewSessionRoute
  '/interview/': typeof InterviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/interview/questions'
    | '/interview/results'
    | '/interview/session'
    | '/interview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/interview/questions'
    | '/interview/results'
    | '/interview/session'
    | '/interview'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/interview/questions'
    | '/interview/results'
    | '/interview/session'
    | '/interview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  InterviewQuestionsRoute: typeof InterviewQuestionsRoute
  InterviewResultsRoute: typeof InterviewResultsRoute
  InterviewSessionRoute: typeof InterviewSessionRoute
  InterviewIndexRoute: typeof InterviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/': {
      id: '/interview/'
      path: '/interview'
      fullPath: '/interview/'
      preLoaderRoute: typeof InterviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/session': {
      id: '/interview/session'
      path: '/interview/session'
      fullPath: '/interview/session'
      preLoaderRoute: typeof InterviewSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/results': {
      id: '/interview/results'
      path: '/interview/results'
      fullPath: '/interview/results'
      preLoaderRoute: typeof InterviewResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/questions': {
      id: '/interview/questions'
      path: '/interview/questions'
      fullPath: '/interview/questions'
      preLoaderRoute: typeof InterviewQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  InterviewQuestionsRoute: InterviewQuestionsRoute,
  InterviewResultsRoute: InterviewResultsRoute,
  InterviewSessionRoute: InterviewSessionRoute,
  InterviewIndexRoute: InterviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
